### ISSUE TITLE
180623[7wd6]开会讨论，确定选题

### ISSUE THREAD

**Issue by bravejiawen** [LexieLee/IA001BP#1]
我们的方向还有点模糊，大家先把关于选题的想法发出来，等到周六的时候进行讨论，时间待定~

把 @LexieLee 最初的想法贴过来了，方便大家参考
![image.png](https://upload-images.jianshu.io/upload_images/3676517-4baca277710a179d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by bravejiawen** [comment]
#### 短视频领域的分析
- 我个人倾向于将项目朝课程组的题目方向里走，对某方面进行分析，然后结果能为我们所用。

- 1、通过分析热门短视频的特点，考虑自身或者企业能够依靠短视频能获得怎样的机会。
  - 品牌如何玩“抖音”，利用抖音营销
  - 什么样的品牌适合在抖音营销
  - 个人有某个方面的能力，如何通过抖音传播自己
  - 未雨绸缪，抖音内容的未来发展方向？
- 2、通过分析短视频公司的行业发展考虑是否换工作转行？？
  
- 如何开展?将涉及到哪些实践策略？
  - APP数据
  
  
参考链接：
  [抖音这么火 , 品牌怎么玩？ @广告门](http://www.adquan.com/post-2-43812.html)
  [3周收获4万粉丝，我们玩抖音的3条经验_36氪](http://36kr.com/p/5077971.html)
  [如何用抖音做营销？_种草_整合营销_整合营销服务_内容营销_品牌传播_社交营销服务_品牌年轻化_时趣互动](http://www.social-touch.com/thinking/default/view?id=59)

**Comment by LexieLee** [comment]
@bravejiawen 佳文分析得棒棒哒！优秀～我发现虽然「短视频」产品有很多，但我们第一个想到的一般是抖音，足以见得抖音品牌营销做得好啊～😂

看了几个抖音的产品分析报告，有些很全面，不少搜集信息的网站可借鉴（如艾瑞指数、七麦数据、ASO100等），或许我们可以从一个小而美的主题切入，不求面面俱到，在小的主题上做文章。先补充一些参考资料，抽空整理想法：

- [深度复盘抖音上线的500天：它如何PK掉了快手和美拍？](http://baijiahao.baidu.com/s?id=1592170403391121162&from=timeline&isappinstalled=0)
- [抖音短视频产品报告_图文_百度文库](https://wenku.baidu.com/view/49302fa5e109581b6bd97f19227916888486b996)
- [“抖音产品分析报告” - PMCAFF产品经理社区 中国第一产品经理人气组织::专注于研究互联网产品](http://www2.pmcaff.com/article/index/1292575384950912?from=related&pmc_param%5Bentry_id%5D=1283835033503872)
- [抖音深度分析报告 | 产品公园](http://pmparker.net/342.html)
- [我抓取了 4 万多条数据，发现抖音爆款视频的秘诀](https://kuaibao.qq.com/s/20180411A0TAGU00?refer=spider)

**Comment by thiinker** [comment]
我也赞同从一个小而美的主题切入。信息分析课程为我们提供了如下与短视频主题相关的方法：
- 找到领域大牛，分析其知识结构
- 公司信息分析
- 公司产品分析
- 个人职业转向
- 社会网络分析
- 识别潜在英才

结合 @bravejiawen 谈到的两个方向，1）分析短视频热门的特点 2）短视频行业发展，我想我们可以从
分析**短视频创作者**入手，主要回答
优秀的短视频创作者/创作团队有哪些，为什么他们创作出了优秀的短视频，他们的知识和技能结构是怎样的？

**Comment by bravejiawen** [comment]
@LexieLee  短视频太火，我们想做的基本网上都有现成的了，你发的这些报告都挺全面的
